source 'https://rubygems.org' do
  gem 'rake'
  gem 'activesupport'
  gem 'oj'
  gem 'json-schema', '>= 2.5.1'
  gem 'deep_merge'
  gem 'gli'

  group :test do
    gem 'rspec', :require => 'spec'
    gem 'simplecov'
    gem 'timecop'
  end

  group :development do
    gem 'geminabox'
    gem 'yard'
    gem 'pry'
  end
end
